### ISSUE TITLE
用不成功

### ISSUE THREAD

**Issue by 245680** [sugarforever/spark-api-gateway#1]
我的是讯飞星火3的key
我将main中入口改成了ws://spark-api.xf-yun.com/v3.1/chat
运行curl例子
返回信息:
{"choices":[{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}],"usage":null}(base)

**Comment by sugarforever** [comment]
星火3的domain是不同的。

```
Tips: 星火大模型API当前有V1.5、V2.0和V3.0三个版本，三个版本独立计量tokens。

星火大模型V1.5请求地址，对应的domain参数为general：

ws(s)://spark-api.xf-yun.com/v1.1/chat
星火大模型V2请求地址，对应的domain参数为generalv2：

ws(s)://spark-api.xf-yun.com/v2.1/chat
星火大模型V3请求地址，对应的domain参数为generalv3：

ws(s)://spark-api.xf-yun.com/v3.1/chat
```

你把domain改了试试 - https://github.com/sugarforever/spark-api-gateway/blob/main/main.py#L56

**Comment by 245680** [comment]
地址改了,domain改了
客户端还是一样,服务端报错
`INFO:     Started server process [3077304]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
### error: Connection to remote host was lost.
 
INFO:     127.0.0.1:58494 - "POST /v1/chat/completions HTTP/1.1" 200 OK`
官方的例子运行是正常的,检查不出和官方例子差别在哪

**Comment by sugarforever** [comment]
```
spark_chat = SparkChat(
        os.environ["APP_ID"],
        os.environ["API_KEY"],
        os.environ["API_SECRET"],
        "ws://spark-api.xf-yun.com/v2.1/chat",
        "generalv2"
    )
```

我测试了星火大模型V2，工作正常。V3模型我没有权限，得到的错误是：

```
请求错误: 11200, {'header': {'code': 11200, 'message': 'AppIdNoAuthError:(01:40:23.406) tokens.total', 'sid': 'cht000ba2a1@dx18b964590edb8f2550', 'status': 2}}
```

你如果是error: Connection to remote host was lost.错误，看起来像是网络连接的问题。我尝试申请下v3的权限再试试。

**Comment by shell-nlp** [comment]
> 地址改了,domain改了 客户端还是一样,服务端报错 `INFO: Started server process [3077304] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
> 
> ### error: Connection to remote host was lost.
> INFO: 127.0.0.1:58494 - "POST /v1/chat/completions HTTP/1.1" 200 OK` 官方的例子运行是正常的,检查不出和官方例子差别在哪

如果你要使用langchain的话，可以使用这个方案,测试是可以的  [url](https://github.com/shell-nlp/spark-ai-python/blob/main/test/spark_langchain.py)
