### ISSUE TITLE
接口调用不成功

### ISSUE THREAD

**Issue by fatwang2** [sugarforever/spark-api-gateway#4]
感谢开发者，非常需要这个项目，但是我不管是用你的api地址，还是我自己部署了一个api地址，调用之后响应都是，不知道是哪里的问题。
```
A server error has occurred

FUNCTION_INVOCATION_FAILED
```

**Comment by sugarforever** [comment]
你好。目前我的部署你可以尝试这样调用

```curl --location 'https://gateway.openai-cloud.com/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "messages": [
        {
            "role": "user",
            "content": "李白最有名的诗是什么？"
        }
    ],
    "model": "spark-api",
    "max_tokens": null,
    "stream": false,
    "n": 1,
    "temperature": 0.7,
    "version": "v2.1"
}'```

你自己部署的是Docker容器吗？可以看看uvicorn的输出，看看是什么错误？

**Comment by fatwang2** [comment]
您好，我是通过postman调用测试的，我自己部署用的是vercel，也试过你的api地址

**Comment by sugarforever** [comment]
你能把postman里的请求code发来看看吗？curl的就行。如果你用了自己的密钥，记得把app id，key，secret这些隐藏掉

**Comment by fatwang2** [comment]
> 你能把postman里的请求code发来看看吗？curl的就行。如果你用了自己的密钥，记得把app id，key，secret这些隐藏掉

服务器上线后的地址+/v1/chat/completions，headers和 body 也都是跟你一样

**Comment by sugarforever** [comment]
那你在本地开发环境能在localhost跑吗？正常不？还是有同样的问题？

**Comment by fatwang2** [comment]
> 那你在本地开发环境能在localhost跑吗？正常不？还是有同样的问题？

你现在用项目里贴的那个vercel的地址可以直接调用吗？

**Comment by sugarforever** [comment]
> > 那你在本地开发环境能在localhost跑吗？正常不？还是有同样的问题？
> 
> 你现在用项目里贴的那个vercel的地址可以直接调用吗？

那个部署我已经停掉了。Vercel上的部署无法支持流式。

你可以尝试这个域名 - gateway.openai-cloud.com

这是我的一个新的部署

**Comment by fatwang2** [comment]
你好，这个域名是可以的，我之前也是在vercel里部署的，看来是不能在vercel上部署？

**Comment by sugarforever** [comment]
vercel可以部署。但是vercel的部署还是以serverless
function的形式服务的，这样就会有10s执行时间的限制。因此时常会有调用失败的情况。

**Comment by fatwang2** [comment]
明白，那我还是用docker自己搭建吧

**Comment by fatwang2** [comment]
这里的imageurl不支持base64的编码，只支持图片url，作者考虑优化么？

**Comment by sugarforever** [comment]
当然。这个可以优化。圣诞假期我抽时间给加上。方便介绍一下，目前你使用这个项目的应用场景吗

**Comment by fatwang2** [comment]
哈哈 我是希望简化我这个项目的代码 https://github.com/fatwang2/sum4all

**Comment by sugarforever** [comment]
nice! 我努力

**Comment by fatwang2** [comment]
感谢

sugarforever ***@***.***>于2023年12月25日 周一08:00写道：

> nice! 我努力
>

**Comment by sugarforever** [comment]
Closing it now as it's not an issue any more. The enhancement mentioned will be tracked by a separate issue.

**Comment by fatwang2** [comment]
您好，请问base64是不是暂时依然不支持，我刚才试了下还是不行

**Comment by sugarforever** [comment]
@fatwang2 , I just used a PR https://github.com/sugarforever/spark-api-gateway/pull/11 to support it.

Please review. You should be able to use the same payload as OpenAI vision API now.
