### ISSUE TITLE
在实际的langchain ChatOpenAI中似乎没有version选项（或者是我用错了），是否可以把version加入模型名字

### ISSUE THREAD

**Issue by Squidward1012** [sugarforever/spark-api-gateway#7]
spark-ai-v3.1解析出v3.1，再加上适当的健壮性代码
![image](https://github.com/sugarforever/spark-api-gateway/assets/95746383/4449ccab-c962-4f37-adc5-566a8d7d3a46)
PR #10

**Comment by sugarforever** [comment]
#10 已合并。

#12 对 Spark API Gateway的模型命名和支持做了重构。
